
name: 'thepetshop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  erp_source: "sql_erp_prod_dbo"
  ofs_source: "mysql_ofs"
  h_ofs_source: "h_mysql_ofs"


models:
  thepetshop:
    
    1_stg:
      +enabled: true
      +materialized: view
      +schema: stg

    2_int:
      +enabled: true
      +materialized: table
      +schema: int

    3_fct:
      +enabled: true
      +materialized: table
      +schema: fct