with 

source_1 as (

    select 

        no_,
        _fivetran_deleted,
        _fivetran_synced,
        _systemid,
        allow_invoice_disc_,
        allow_online_adjustment,
        alternative_item_no_,
        application_wksh__user_id,
        assembly_policy,
        automatic_ext__texts,
        base_unit_of_measure,
        block_reason,
        blocked,
        budget_profit,
        budget_quantity,
        budgeted_amount,
        commission_group,
        common_item_no_,
        cost_is_adjusted,
        costing_method,
        country_region_of_origin_code,
        country_region_purchased_code,
        created_from_nonstock_item,
        critical,
        dampener_period,
        dampener_quantity,
        default_deferral_template_code,
        description,
        description_2,
        discrete_order_quantity,
        durability,
        duty_code,
        duty_due__,
        duty_unit_conversion,
        expiration_calculation,
        flushing_method,
        freight_type,
        gen__prod__posting_group,
        global_dimension_1_code,
        global_dimension_2_code,
        gross_weight,
        gtin,
        id,
        include_inventory,
        indirect_cost__,
        inventory_posting_group,
        inventory_value_zero,
        item_category_code,
        item_category_id,
        item_disc__group,
        item_tracking_code,
        last_counting_period_update,
        last_date_modified,
        last_datetime_modified,
        last_direct_cost,
        last_time_modified,
        last_unit_cost_calc__date,
        lead_time_calculation,
        lot_accumulation_period,
        lot_nos_,
        lot_size,
        low_level_code,
        manufacturer_code,
        manufacturing_policy,
        maximum_inventory,
        maximum_order_quantity,
        minimum_order_quantity,
        net_weight,
        next_counting_end_date,
        next_counting_start_date,
        no__2,
        no__series,
        order_multiple,
        order_tracking_policy,
        over_receipt_code,
        overflow_level,
        overhead_rate,
        phys_invt_counting_period_code,
        picture,
        prevent_negative_inventory,
        price_includes_vat,
        price_profit_calculation,
        price_unit_conversion,
        product_group_code,
        production_bom_no_,
        profit__,
        purch__unit_of_measure,
        purchasing_blocked,
        purchasing_code,
        put_away_template_code,
        put_away_unit_of_measure_code,
        reorder_point,
        reorder_quantity,
        reordering_policy,
        replenishment_system,
        rescheduling_period,
        reserve,
        rolled_up_cap__overhead_cost,
        rolled_up_capacity_cost,
        rolled_up_material_cost,
        rolled_up_mfg__ovhd_cost,
        rolled_up_subcontracted_cost,
        rounding_precision,
        routing_no_,
        safety_lead_time,
        safety_stock_quantity,
        sales_blocked,
        sales_unit_of_measure,
        scrap__,
        search_description,
        serial_nos_,
        service_item_group,
        shelf_no_,
        single_level_cap__ovhd_cost,
        single_level_capacity_cost,
        single_level_material_cost,
        single_level_mfg__ovhd_cost,
        single_level_subcontrd__cost,
        special_equipment_code,
        standard_cost,
        statistics_group,
        stockout_warning,
        tariff_no_,
        tax_group_code,
        tax_group_id,
        time_bucket,
        timestamp,
        type,
        unit_cost,
        unit_list_price,
        unit_of_measure_id,
        unit_price,
        unit_volume,
        units_per_parcel,
        use_cross_docking,
        vat_bus__posting_gr___price_,
        vat_prod__posting_group,
        vendor_item_no_,
        vendor_no_,
        warehouse_class_code

    
    from {{ source('sql_erp_prod_dbo', 'petshop_item_437dbf0e_84ff_417a_965d_ed2bb9650972') }}

),



source_2 as (

   select
        no_,
        _fivetran_deleted,
        _fivetran_synced,
        abc_profit,
        abc_sales,
        ask_for_tare,
        attrib_1_code,
        attrib_2_code,
        attrib_3_code,
        attrib_4_code,
        attrib_5_code,
        available_as_dish,
        barcode_mask,
        base_comp__unit_code,
        bom_cost_price_distribution,
        bom_method,
        bom_receipt_print,
        bom_receiving_explode,
        bom_type,
        comp__price_incl__vat,
        comparison_unit_code,
        confidence_factor_code,
        created_by_user,
        date_created,
        def__ordered_by,
        def__ordering_method,
        default_tare_weight,
        dimension_pattern_code,
        dispense_printer_group,
        division_code,
        effective_inv__purchase_ord_,
        effective_inv__sales_order,
        effective_inv__transfer_inb_,
        effective_inv__transfer_outb_,
        error_check_internal_usage,
        exclude_from_menu_requisition,
        exclude_from_replenishment,
        excluded_from_portion_weight,
        explode_bom_in_statem__posting,
        extern__size_crust,
        external_item_no_,
        food_stamp_applicable,
        fuel_item,
        item_capacity_value,
        item_error_check_code,
        item_error_check_status,
        item_family_code,
        keying_in_price,
        keying_in_quantity,
        last_modified_by_user,
        lifecycle_curve_code,
        lifecycle_ending_date,
        lifecycle_length,
        lifecycle_starting_date,
        like_for_like_process_method,
        like_for_like_replen__method,
        ls_forecast_calc__horizon,
        ls_forecast_method,
        manual_estimated_daily_sale,
        max__ingr____modifiers,
        max__ingr__removed_no_price,
        max__modifiers_no_price,
        no_discount_allowed,
        no_stock_posting,
        original_vendor_item_no_,
        original_vendor_no_,
        pos_cost_calculation,
        print_variants_shelf_labels,
        production_time__min__,
        profit_goal__,
        purch__order_delivery,
        qty__becomes_negative,
        qty__per_base_comp__unit,
        qty_not_in_decimal,
        recipe_category,
        recipe_item_type,
        recipe_main_ingredient,
        recipe_no__of_portions,
        recipe_style,
        recipe_version_code,
        replen__data_profile,
        replen__transfer_rule_code,
        replenish_as_item_no_,
        replenish_as_item_no___method,
        replenishment_calculation_type,
        replenishment_grade_code,
        replenishment_sales_profile,
        retail_product_code,
        safety_stock_calculation,
        scale_item,
        season_code,
        select_lowest_price_vendor,
        skip_compression_when_printed,
        skip_compression_when_scanned,
        store_coverage_days_profile,
        store_forward_sales_profile,
        store_stock_cover_reqd__days_,
        suggested_qty__on_pos,
        tare_weight,
        timestamp,
        transfer_multiple,
        unaff__by_multipl__factor,
        unit_price_including_vat,
        uom_pop_up_on_pos,
        upd__cost_and_weight_w_posting,
        use_ean_standard_barc_,
        variant_framework_code,
        wareh__forward_sales_profile,
        wareh_coverage_days_profile,
        wareh_stock_cover_reqd__days_,
        warranty_card,
        wastage__,
        wic_applicable,
        zero_price_valid


from {{ source('sql_erp_prod_dbo', 'petshop_item_5ecfc871_5d82_43f1_9c54_59685e82318d') }}


),

source_3 as (

    select
        no_,
        _fivetran_deleted,
        _fivetran_synced,
        arabicdescripation,
        average_purch__cost,
        b2b,
        binsize,
        brand,
        danger,
        enable_disable,
        error_msg,
        fragile,
        grade,
        group_item_no_,
        image_synced,
        image_url,
        item_sub_category,
        itemsynced,
        last_synced_with_web_at,
        long_description,
        modified_synced_with_web,
        ofserrormessage,
        ofsretrycount,
        ofssynced,
        ofssynceddatetime,
        ofssyncederror,
        online,
        packet_unit_of_measure,
        pos,
        ps_classification,
        purchase_type,
        qcinstruction,
        sales_price_synced,
        sales_price_synced_retry,
        sales_price_syncing_error,
        sku_no_,
        sync_with_web,
        synced_with_web_at,
        synced_with_web_retry,
        --timestamp,
        varient_code,
        varient_item,
        vendor_name,
        vendor_type,
        wmserrormessage,
        wmsretrycount,
        wmssynced,
        wmssynceddatetime,
        wmssyncederror,
        shopify_item_id,
        master_replenishable_item,
        pallet,
        top_400,
        --case,
        layer,
        profit_margin_in_aed,
        shopify_inventory_id,
        cbm,
        initial_shelf_life__days_,
        quantity_for_linked_item,
        buying_price,
        disable_for_slimstock,
        arabic_name,
        cbm__d_,
        quantity_for_linked_items,
        shopify_b2b_item_id,
        b2b_copy_id,
        shopify_b2b_inventory_id


    from {{ source('sql_erp_prod_dbo', 'petshop_item_c91094c2_db03_49d2_8cb9_95c179ecbf9d') }}
),

tariff_number as (
    select
        no_,
        _fivetran_deleted,
        _fivetran_synced,
        _systemid,
        description,
        supplementary_units,
        timestamp
     from {{ source('sql_erp_prod_dbo', 'petshop_tariff_number_437dbf0e_84ff_417a_965d_ed2bb9650972') }}
)

select
            a.no_ AS item_no_,
            a.description AS item_name,
            e.brand AS item_brand,
            A.inventory_posting_group,
            
            A.no__2 AS OldItemNo,
            A.vendor_no_ AS VendorNo,
            A.vendor_item_no_ AS VendorItemNo,
            C.original_vendor_item_no_ AS OriginalVendorItemNo,
            E.ps_classification AS PS_Classification_Code,
            A.blocked,

            e.varient_item,

            
            

            
            E.grade AS Grade,
            A.unit_cost,
            A.unit_price,
            A.base_unit_of_measure AS Base_Unit_of_Measure,
            E.packet_unit_of_measure AS Packet_Unit_Of_Measure,
            A.safety_stock_quantity,
            A.tariff_no_ AS Tariff_No,

            a.item_category_code,
            c.retail_product_code,

            c.division_code,

            F.description AS Tariff_Description,

from source_1 as a
left join source_2 as c on a.no_ =c.no_
left join source_3 as e on a.no_ =e.no_
left join tariff_number as f on a.tariff_no_ = f.no_

--where a.no_ = '300104-1'