with 

source as (

    select * from {{ source('mysql_ofs', 'orderdataanalysis') }}

),

renamed as (

    select
        id,
        weborderno,
        referenceorderno,
        orderdate,
        country,
        ordertype,
        ordercategory,
        itemid,
        sku,
        batchid,
        batchdatetime,
        ispna,
        picked,
        pickedbarcode,
        pickbin,
        pickeddatetime,
        pickedby,
        allocated,
        allocateddatetime,
        allocatedby,
        boxid,
        boxdatetime,
        packedby,
        awbno,
        dspcode,
        orderamount,
        invoiceno,
        invoicedate,
        invoiceamount,
        invoiceamount_usd,
        storecredit,
        collectableamount,
        collectableamount_usd,
        manifestno,
        manifestdate,
        iscancelled,
        ishold,
        paymentmethodcode,
        paymentgateway,
        transactionid,
        transctionamount,
        paymentdate,
        deliverydate,
        dspcashreceived,
        dsponlinereceived,
        forwardcycleclose,
        returninitiatedate,
        pnr,
        returntype,
        returndsp,
        returnticket,
        returnawbno,
        refundamount,
        refundpaymentmethod,
        returntransactionid,
        returntransactiondate,
        qcstatus,
        returncycleclose,
        readyforarchive,
        returnqcdate,
        isdelivered,
        isshipped,
        ispaymentreceived,
        agentcode,
        agentcommission,
        invoiceamount_kwd,
        storecredit_kwd,
        collectableamount_kwd,
        isbypassqc,
        issync,
        syncdatetime,
        syncretrycount,
        syncerrormessage,
        isgateentry,
        returnbeforedelivery,
        returngateentrydate,
        isreturn,
        customerid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
--where weborderno= 'O30114277S'