select

source_no_,
name,
raw_phone_no_,
customer_identity_status,
customer_acquisition_date,
first_order_date,
last_order_date,
stores_used,
platforms_used,
total_order_count,
online_order_count,
offline_order_count,
total_sales_value,
online_sales_value,
offline_sales_value,
ytd_sales,
mtd_sales,
first_acquisition_store,
first_acquisition_platform,
customer_acquisition_channel,
recency_days,
customer_tenure_days,
frequency_orders,
monetary_total_value,
monetary_avg_order_value,
avg_monthly_demand,
customer_type,
customer_channel_distribution,
acquisition_cohort,
acquisition_cohort_rank,

--r_score,
--f_score,
--m_score,
--rfm_segment,
customer_value_segment,
customer_rfm_segment,
customer_acquisition_channel_detail,

months_since_acquisition,


from {{ ref('int_customer_transaction_model') }}
