version: 2

models:
  - name: fct_product_pairs
    description: "Fact table of distinct product pairs that co-occur within the same order. Generated via self-join on int_mba_order_items with product1_id < product2_id to avoid duplicates. Includes all product attributes for both items in the pair and the count of orders containing both."
    columns:
      - name: product1_id
        description: "Identifier for the first product in the pair (lower product_id)."
        tests:
          - not_null
      - name: product1_name
        description: "Name of the first product."
      - name: product1_division
        description: "Division of the first product."
      - name: product1_category
        description: "Category of the first product."
      - name: product1_subcategory
        description: "Subcategory of the first product."
      - name: product1_brand
        description: "Brand of the first product."
      - name: product2_id
        description: "Identifier for the second product in the pair (higher product_id)."
        tests:
          - not_null
      - name: product2_name
        description: "Name of the second product."
      - name: product2_division
        description: "Division of the second product."
      - name: product2_category
        description: "Category of the second product."
      - name: product2_subcategory
        description: "Subcategory of the second product."
      - name: product2_brand
        description: "Brand of the second product."
      - name: pair_order_count
        description: "Number of distinct orders that include both products together."
        tests:
          - not_null

  - name: fct_product_pair_metrics
    description: "Market Basket Analysis metrics table containing support and confidence calculations for each product pair. Support measures how frequently the pair appears together, while confidence measures the likelihood of purchasing one product given the other."
    columns:
      - name: product1_id
        description: "Identifier for the antecedent product in the association rule."
        tests:
          - not_null
      - name: product2_id
        description: "Identifier for the consequent product in the association rule."
        tests:
          - not_null
      - name: pair_order_count
        description: "Number of orders containing both products together."
      - name: product1_order_count
        description: "Total number of distinct orders containing product 1."
      - name: product2_order_count
        description: "Total number of distinct orders containing product 2."
      - name: total_orders
        description: "Total number of sale orders in the dataset."
      - name: support
        description: "Support measure: pair_order_count / total_orders. Indicates frequency of the pair across all transactions."
      - name: confidence_p1_to_p2
        description: "Confidence that product 2 is purchased given product 1 was purchased: pair_order_count / product1_order_count."
      - name: confidence_p2_to_p1
        description: "Confidence that product 1 is purchased given product 2 was purchased: pair_order_count / product2_order_count."

  - name: fct_pareto_items
    description: "Pareto analysis fact table providing revenue-based ranking metrics across six merchandising dimensions (global, primary_sales_channel, division, category, subcategory, brand). For each dimension, calculates revenue, dense rank, and cumulative revenue percentage to support 80/20 analysis and identify top performers."
    config:
      materialized: table
    columns:
      - name: item_id
        description: "Unique identifier for the item."
        tests:
          - not_null
          - unique
      - name: item_name
        description: "Business-friendly item name."
      - name: primary_sales_channel
        description: "Primary channel through which the item sells (Online, Shop, Affiliate, None)."
      - name: division
        description: "Top-level merchandise division for the item."
      - name: category
        description: "Category for the item."
      - name: subcategory
        description: "Subcategory for the item."
      - name: brand
        description: "Brand for the item."
      - name: revenue_per_global
        description: "Item revenue used for global ranking."
      - name: rank_global
        description: "Dense rank of the item based on revenue across all items globally."
      - name: cumulative_pct_global
        description: "Cumulative revenue percentage globally (used to identify top 20% contributors)."
      - name: revenue_per_primary_sales_channel
        description: "Item revenue used for ranking within its primary sales channel."
      - name: rank_primary_sales_channel
        description: "Dense rank within the item's primary sales channel."
      - name: cumulative_pct_primary_sales_channel
        description: "Cumulative revenue percentage within the primary sales channel."
      - name: revenue_per_division
        description: "Item revenue used for ranking within its division."
      - name: rank_division
        description: "Dense rank within the item's division."
      - name: cumulative_pct_division
        description: "Cumulative revenue percentage within the division."
      - name: revenue_per_category
        description: "Item revenue used for ranking within its category."
      - name: rank_category
        description: "Dense rank within the item's category."
      - name: cumulative_pct_category
        description: "Cumulative revenue percentage within the category."
      - name: revenue_per_subcategory
        description: "Item revenue used for ranking within its subcategory."
      - name: rank_subcategory
        description: "Dense rank within the item's subcategory."
      - name: cumulative_pct_subcategory
        description: "Cumulative revenue percentage within the subcategory."
      - name: revenue_per_brand
        description: "Item revenue used for ranking within its brand."
      - name: rank_brand
        description: "Dense rank within the item's brand."
      - name: cumulative_pct_brand
        description: "Cumulative revenue percentage within the brand."

