
with source as (
select 
    a.*,
    d.dimension_code,
    d.name as global_dimension_2_code_name,
    d.name as clc_global_dimension_2_code_name

    from {{ source('sql_erp_prod_dbo', 'the_petshop_cafe_value_entry_437dbf0e_84ff_417a_965d_ed2bb9650972') }} as a
    left join {{ source('sql_erp_prod_dbo', 'the_petshop_cafe_dimension_value_437dbf0e_84ff_417a_965d_ed2bb9650972') }} as d on a.global_dimension_2_code = d.code and d.global_dimension_no_ = 2

)
,

renamed as (
    select
        entry_no_,
        document_date,
        exp__cost_posted_to_g_l__acy_,
        user_id,
        source_code,
        location_code,
        gen__prod__posting_group,
        order_line_no_,
        document_type,
        inventory_posting_group,
        salespers__purch__code,
        valued_quantity,
        posting_date,
        valuation_date,
        cost_amount__expected_,
        expected_cost_posted_to_g_l,
        no_,
        sales_amount__expected_,
        invoiced_quantity,
        adjustment,
        _systemid,
        item_ledger_entry_quantity,
        cost_amount__actual___acy_,
        order_no_,
        purchase_amount__expected_,
        cost_per_unit,
        cost_amount__non_invtbl___acy_,
        cost_amount__non_invtbl__,
        job_task_no_,
        source_posting_group,
        item_ledger_entry_type,
        gen__bus__posting_group,
        average_cost_exception,
        item_no_,
        description,
        source_no_,
        applies_to_entry,
        cost_posted_to_g_l,
        job_ledger_entry_no_,
        variant_code,
        source_type,
        discount_amount,
        cost_per_unit__acy_,
        cost_amount__expected___acy_,
        variance_type,
        expected_cost,
        entry_type,
        inventoriable,
        global_dimension_2_code,
        valued_by_average_cost,
        sales_amount__actual_,
        return_reason_code,
        document_no_,
        capacity_ledger_entry_no_,
        cost_posted_to_g_l__acy_,
        timestamp,
        journal_batch_name,
        purchase_amount__actual_,
        item_charge_no_,
        item_ledger_entry_no_,
        external_document_no_,
        cost_amount__actual_,
        order_type,
        job_no_,
        type,
        reason_code,
        dimension_set_id,
        partial_revaluation,
        document_line_no_,
        drop_shipment,
        global_dimension_1_code,
        _fivetran_deleted,
        _fivetran_synced,
        dimension_code,
        global_dimension_2_code_name,
        clc_global_dimension_2_code_name,

    from source
) 


    select * from renamed